services:
  mega-client:
    image: mega-client:latest
    container_name: mega-client
    user: 1000:1000
    ports:
      - 3000:3000
    volumes:
      - /Users/bo/Downloads:/downloads
      - $HOME/.megaCmd:/root/.megaCmd
    environment:
      DOWNLOAD_PATH: /downloads
